### ISSUE TITLE
Improve errors from weather

### ISSUE THREAD

**Issue by fhunleth** [elixir-toolshed/toolshed#125]
`weather` is being used to check if the internet works on Nerves. Giving better error messages when the network doesn't work or DNS fails would be helpful.

**Comment by mnishiguchi** [comment]
How about ping once within the `weather/0` to check the network? We could repurpose `tping/2`'s logic.
https://github.com/elixir-toolshed/toolshed/blob/fba8e62645acdc17b46a03159186aeae253e9b82/lib/toolshed/tcp_ping.ex#L29-L36

**Comment by fhunleth** [comment]
I think that I should have been more specific when writing this up. If I remember right, if you don't have internet access and try running `weather`, you get an exception. I was just thinking that it would be nice to catch the exception or translate the error into a friendlier message. I don't think that any network diagnostics need to be done.
