### ISSUE TITLE
Improve API reference

### ISSUE THREAD

**Issue by mnishiguchi** [elixir-toolshed/toolshed#131]
Currently API reference is not easy to consult when we need to find a specific function. The top-level `Toolshed` module contains only a few so we need to figure out which other module houses functions we are searching for.

![](https://user-images.githubusercontent.com/7563926/176802712-f57c3034-7274-441f-a251-c993048907a8.png)

One idea to improve the function discoverability is to place all the functions in the top-level `Toolshed` module, which can be achievable simply doing delegation (`defdelegate` or explicitly call the submodule functions). How does it sound?

![](https://user-images.githubusercontent.com/7563926/176802691-256f0a40-fbbf-4ab8-aaf5-a2bf42d6fea3.png)

Another benefit would be testability of `use Toolshed` making all the functions available properly.

![](https://user-images.githubusercontent.com/7563926/176806202-508b6c25-e4fa-401d-9b15-11e1067e3a2c.png)

Maybe https://github.com/elixir-toolshed/toolshed/issues/60 is good enough? 🤔

**Comment by fhunleth** [comment]
This sounds like a great improvement to me. It's always bothered me that all of the functions wouldn't should up in the root module.
