### ISSUE TITLE
Add poweroff utility

### ISSUE THREAD

**Issue by fhunleth** [elixir-toolshed/toolshed#149]
This would be a shortcut to [`Nerves.Runtime.poweroff/0`](https://hexdocs.pm/nerves_runtime/Nerves.Runtime.html#poweroff/0).

It came up several times at ElixirConf when people were wanting to gracefully power off their devices.

**Comment by okothkongo** [comment]
@fhunleth can I take up this?
I believe the intent here is to stop the Beam by calling :init.stop/0 under the hood

**Comment by fhunleth** [comment]
@okothkongo Thanks for the offer. This is a pretty simple Nerves helper. If you don't have a Raspberry Pi convenient, how about let me or Masa implement it this time. We're trying to wrap up some bigger changes and after those are done and we get a chance, we'll be posting more issues that might be better for you to try.

**Comment by okothkongo** [comment]
@fhunleth at the moment I dont Raspberry Pi.Sure go ahead, I will be waiting for the new issues.

**Comment by fhunleth** [comment]
Fixed in #171
