### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by fhunleth** [elixir-toolshed/toolshed#58]
Very little of toolshed is unit tested and this is not ideal for long term maintenance. Since many of the tools just wrap functions that can be presumed tested, I don't think that it's necessary to test the functionality deeply. Perhaps only test that the helper exists and passing an argument basically works. 

It would be good to write tests for one or two helpers first to how this looks and how valuable it is.

**Comment by mnishiguchi** [comment]
I think it is worth it to minimally test at least one happy path for each function. Also that effort might reveal some room for improvement. I'll write some minimal tests.

**Comment by fhunleth** [comment]
Closing since basic unit tests for many functions are in place now and we can improve in future PRs.
